SELECT SNAME, TERM, MARK-(SELECT avg(MARK) AS AVERAGE
FROM ENROLLMENT
WHERE TERM LIKE '%10'
AND CNO = 'CS348' GROUP BY CNO) 
FROM STUDENT NATURAL JOIN ENROLLMENT
WHERE TERM LIKE '%10'
AND CNO = 'CS348';