SELECT DISTINCT CNO FROM ENROLLMENT
WHERE TERM LIKE '%09'
AND CNO NOT IN 
(SELECT CNO FROM
	(SELECT CNO,avg(MARK) AS AVERAGE FROM ENROLLMENT 
	WHERE TERM LIKE '%09'
	GROUP BY TERM,CNO,SECTION)
WHERE AVERAGE <= 80)
ORDER BY CNO;
