SELECT SNO, AVG(MARK)
FROM ENROLLMENT
WHERE SNO IN (SELECT SNO FROM ENROLLMENT 
	NATURAL JOIN 
	(SELECT CNO, TERM, SECTION FROM ENROLLMENT
	GROUP BY CNO, TERM, SECTION
	HAVING COUNT(*) > 20)
	GROUP BY SNO
	HAVING COUNT(*) >= 3)
AND SNO NOT IN (SELECT SNO FROM ENROLLMENT
				NATURAL JOIN
				(SELECT CNO, TERM, SECTION FROM ENROLLMENT
			GROUP BY CNO, TERM, SECTION 
			HAVING COUNT(*) > 20)
		WHERE MARK < 85)
AND SNO IN (SELECT SNO FROM ENROLLMENT
		WHERE MARK > 70
		GROUP BY SNO
		HAVING COUNT(*) > 10)
GROUP by SNO;
